### PR TITLE
Active new field mappings

### PR DESCRIPTION
**Pull request by BeNeDeLuX**
## Description

This change activates the new field assignments. And yes, that could break things!
Because the fields are no longer named as keyword fields like "unbound.query.client.ip.keyword" is now -> "unbound.query.client.ip" and the field type is e.g. IP. 

I changed all fields I found that contain a number to the type number. The same applies to the IP fields.
Now we can calculate with the numbers, group the number (e.g. status code 200-299), use IP ranges and so on.

The visualization in the dashboards has to be adapted quickly to the new field name. In most cases it is enough to remove ".keyword" to get it working again. I will check the one after one.

Fixes # (issue)

- Wrong field types 

## Type of change

Please delete options that are not relevant.

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by BeNeDeLuX** [comment]
Would be great if someone (with a new installation) could check it again

**Comment by a3ilson** [comment]
@BeNeDeLuX - Thanks!  

I plan on doing the same for suricata that will allow the SIEM plugin (dashboards)...just haven't had the time (transiting jobs).  I'll test and update the corresponding dashboards within the next week or two.

**Comment by rrosson** [comment]
Having pfelk using the SIEM that is built into elastic will be a huge bonus. I look forward to seeing this evolve.

**Comment by a3ilson** [comment]
@BeNeDeLuX - Thanks!  
There were a number of changes and your efforts for mapping the fields made quick work of tweaking and finalizing. I closed this merge as the complexity of the changes to both the fields names (conf and grok pattern files) and templates incorporated and built upon this merge request.
Thanks 🥇

**Pull request closed without merging**
