### PR TITLE
Update pfelk_rule_generator.sh

### PR DESCRIPTION
**Pull request by ShagoY**
## Description

Change path URL for pfelk_rule_sync.sh

### CODE REVIEW

**Comment by ShagoY** [comment]
Oh my god, sorry I wanted to create two different pull requests... But I couldn't do it.

So for "Update 20-interfaces.conf", I added the fallback and after testing it works very well on my fork.
It allows you to fill in the [interface][alias] and [network][name] fields directly after an installation (without even modifying the file according to its network configuration).

The filters "![interface][alias] and [interface][name]" allow to add these new fields only for logs coming from filterlog.

**Comment by a3ilson** [comment]
I just updated my local setup...works great/thanks!

**Comment by a3ilson** [comment]
Any chance your running pfSense and willing/able to test out a modified 03-filter.conf (i.e. GROK pattern to accommodate for BSD/Syslog log outputs? (Issue #243)

**Comment by ShagoY** [comment]
Sorry I use OPNsense.

And I'm bad at templates/patterns/grok/etc... ^^

**Comment by a3ilson** [comment]
Same (OPNsense)... Just hoping someone with pfSense will test/validate, so I can close out. Thanks anyways and thanks for your contribution and continued support!

**Pull request merged**
