### PR TITLE
NGINX onboarding

### PR DESCRIPTION
**Pull request by BeNeDeLuX**
# Pull Request Template

## Description

First config addon's for NGINX Logs. Documentation is following 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update -> i will provide a documentation for OPNsense

## Checklist:

- [X] Code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by a3ilson** [comment]
Let me know if the revised 30-geoip.conf file works. Once confirmed I'll merge the PR. I will also update the mappings to include nginx fields for ECS.

**Comment by a3ilson** [comment]
Creating/adding mappings to the field mappings. Had a few fields that need to be clarified:

- `%{QS:[nginx][access][forwarder]}`
  - Is this supposed to be `nginx.ingress_controller.remote_ip_list`? Please take a look at the data and see which field it best resides [NGINX Fields](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-nginx.html)
- `{DATA:[nginx][access][http_server]}`
  - Is this supposed to be `nginx.ingress_controller.upstream_address_list`? Please take a look at the data and see which field it best resides [NGINX Fields](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-nginx.html)
- `{DATA:[nginx][ingress_controller][upstream][cachestatus]}`
  - There are a few "status_code" fields but no referenced "cachestatus" ones. Take a look at the following and see which one works best:
  - `nginx.ingress_controller.upstream.response.status_code_list`
  - `nginx.ingress_controller.upstream.response.status_code`
  - `nginx.ingress_controller.response_code`
  - Description for each field can be found [here](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-nginx.html)

Once we get these clarified, I'll update the field mappings which will likely require you to flush your index, apply the new filter and rebuild/revise the proposed dashboard.

**Comment by BeNeDeLuX** [comment]
Here is the field list from the OPNsense config file for the defined log format:
```

log_format  main_ext  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '
                      '"$host" sn="$server_name" '
                      'rt=$request_time '
                      'ua="$upstream_addr" us="$upstream_status" '
                      'ut="$upstream_response_time" ul="$upstream_response_length" '
                      'cs=$upstream_cache_status';

```
I'm not 100% sure with the fields mapping:

`{QS:[nginx][access][forwarder]} `-> `nginx.access.remote_ip_list` ("$http_x_forwarded_for")
`{DATA:[nginx][access][http_server]} `-> is the external hostname (host.domain.tld) to which was connected ("$host") and is the same value as `nginx.ingress_controller.upstream.name` in my case.
`{DATA:[nginx][ingress_controller][upstream][cachestatus]} `-> there exists no field inside the ECS field reference ("cs=$upstream_cache_status")

**Comment by a3ilson** [comment]
Mappings built. Please update your mappings with the following. Once installed, you may need to purge the index and associated saved objects - please test and validate. Once confirmed, you'll most likely need to rebuild the dashboard and once updated, I'll merge this pull request.

```
PUT _index_template/pfelk-nginx
{
  "version": 22,
  "priority": 295,
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "pfelk"
        }
      }
    },
    "mappings": {
      "_routing": {
        "required": false
      },
      "numeric_detection": false,
      "_source": {
        "excludes": [],
        "includes": [],
        "enabled": true
      },
      "dynamic": true,
      "dynamic_templates": [],
      "date_detection": false,
      "properties": {
        "nginx": {
          "type": "object",
          "properties": {
            "access": {
              "type": "object",
              "properties": {
                "referrer": {
                  "type": "keyword"
                },
                "agent": {
                  "type": "keyword"
                },
                "response_code": {
                  "type": "long"
                },
                "geoip": {
                  "dynamic": true,
                  "type": "object",
                  "enabled": true,
                  "properties": {
                    "continent_name": {
                      "type": "keyword"
                    },
                    "region_iso_code": {
                      "type": "keyword"
                    },
                    "city_name": {
                      "type": "keyword"
                    },
                    "country_iso_code": {
                      "type": "keyword"
                    },
                    "location": {
                      "type": "geo_point"
                    },
                    "region_name": {
                      "type": "keyword"
                    }
                  }
                },
                "method": {
                  "type": "keyword"
                },
                "user_name": {
                  "type": "keyword"
                },
                "http_version": {
                  "type": "keyword"
                },
                "body_sent": {
                  "type": "object",
                  "properties": {
                    "bytes": {
                      "type": "long"
                    }
                  }
                },
                "remote_ip_list": {
                  "index": true,
                  "store": false,
                  "type": "ip",
                  "doc_values": true
                },
                "url": {
                  "type": "wildcard"
                },
                "user_agent": {
                  "type": "object",
                  "properties": {
                    "original": {
                      "type": "keyword"
                    },
                    "os": {
                      "type": "keyword"
                    },
                    "name": {
                      "type": "keyword"
                    },
                    "os_name": {
                      "type": "keyword"
                    },
                    "device": {
                      "type": "keyword"
                    }
                  }
                }
              }
            },
            "ingress_controller": {
              "type": "object",
              "properties": {
                "request": {
                  "type": "object",
                  "properties": {
                    "length": {
                      "type": "long"
                    },
                    "time": {
                      "type": "double"
                    }
                  }
                },
                "agent": {
                  "type": "keyword"
                },
                "response_code": {
                  "type": "long"
                },
                "geoip": {
                  "type": "object",
                  "properties": {
                    "continent_name": {
                      "type": "keyword"
                    },
                    "region_iso_code": {
                      "type": "keyword"
                    },
                    "city_name": {
                      "type": "keyword"
                    },
                    "country_iso_code": {
                      "type": "keyword"
                    },
                    "location": {
                      "type": "geo_point"
                    },
                    "region_name": {
                      "type": "keyword"
                    }
                  }
                },
                "upstream": {
                  "type": "object",
                  "properties": {
                    "alternative_name": {
                      "type": "keyword"
                    },
                    "port": {
                      "type": "long"
                    },
                    "response": {
                      "type": "object",
                      "properties": {
                        "status_code": {
                          "type": "long"
                        },
                        "length": {
                          "type": "long"
                        },
                        "length_list": {
                          "type": "keyword"
                        },
                        "status_code_list": {
                          "type": "keyword"
                        },
                        "time": {
                          "coerce": true,
                          "index": true,
                          "ignore_malformed": false,
                          "store": false,
                          "type": "double",
                          "doc_values": true
                        },
                        "time_list": {
                          "type": "keyword"
                        }
                      }
                    },
                    "ip": {
                      "type": "ip"
                    },
                    "name": {
                      "type": "keyword"
                    }
                  }
                },
                "method": {
                  "type": "keyword"
                },
                "user_name": {
                  "type": "keyword"
                },
                "http_version": {
                  "type": "keyword"
                },
                "remote_ip_list": {
                  "eager_global_ordinals": false,
                  "norms": false,
                  "index": true,
                  "store": false,
                  "type": "keyword",
                  "index_options": "docs",
                  "split_queries_on_whitespace": false,
                  "doc_values": true
                },
                "url": {
                  "type": "wildcard"
                },
                "referrer": {
                  "type": "keyword"
                },
                "upstream_address_list": {
                  "type": "keyword"
                },
                "http": {
                  "type": "object",
                  "properties": {
                    "request": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "keyword"
                        }
                      }
                    }
                  }
                },
                "body_sent": {
                  "type": "object",
                  "properties": {
                    "bytes": {
                      "type": "long"
                    }
                  }
                },
                "user_agent": {
                  "type": "object",
                  "properties": {
                    "original": {
                      "type": "keyword"
                    },
                    "os": {
                      "type": "keyword"
                    },
                    "name": {
                      "type": "keyword"
                    },
                    "os_name": {
                      "type": "keyword"
                    },
                    "device": {
                      "type": "keyword"
                    }
                  }
                }
              }
            },
            "error": {
              "type": "object",
              "properties": {
                "process": {
                  "type": "long"
                },
                "connection_id": {
                  "type": "long"
                },
                "level": {
                  "type": "keyword"
                },
                "message": {
                  "type": "text"
                },
                "tid": {
                  "type": "long"
                }
              }
            }
          }
        }
      }
    }
  },
  "index_patterns": [
    "*-pfelk-nginx*"
  ],
  "data_stream": {
    "hidden": false
  },
  "composed_of": [
    "pfelk-settings",
    "pfelk-mappings-ecs"
  ],
  "_meta": {
    "description": "default nginx indexes installed by pfelk",
    "managed": true
  }
}
```

**Comment by BeNeDeLuX** [comment]
@a3ilson - Wow, thanks! This looks great so far.
There is one field `nginx.ingress_controller.http.request.time` that's type is "text" instead of "number".
Bildschirmfoto_2022-01-07_19-51-00
If you could also add this field as type number ? Then i could add some more content to the dashboard. Currently i can´t calculate with it.


Here is my current dashboard status. 
Added also filters on the top for the HTTP & Upstream Server. This makes it easy to filter single instances and display the relations between backend & frontend.
screenshot_nginx_db_2

**Comment by a3ilson** [comment]
I had that nested in the wrong area... try this one:

```
PUT _index_template/pfelk-nginx
{
  "version": 22,
  "priority": 295,
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "pfelk"
        }
      }
    },
    "mappings": {
      "_source": {
        "excludes": [],
        "includes": [],
        "enabled": true
      },
      "_routing": {
        "required": false
      },
      "dynamic": true,
      "numeric_detection": false,
      "date_detection": false,
      "dynamic_templates": [],
      "properties": {
        "nginx": {
          "type": "object",
          "properties": {
            "access": {
              "type": "object",
              "properties": {
                "agent": {
                  "type": "keyword"
                },
                "body_sent": {
                  "type": "object",
                  "properties": {
                    "bytes": {
                      "type": "long"
                    }
                  }
                },
                "geoip": {
                  "dynamic": true,
                  "type": "object",
                  "enabled": true,
                  "properties": {
                    "city_name": {
                      "type": "keyword"
                    },
                    "continent_name": {
                      "type": "keyword"
                    },
                    "country_iso_code": {
                      "type": "keyword"
                    },
                    "location": {
                      "type": "geo_point"
                    },
                    "region_iso_code": {
                      "type": "keyword"
                    },
                    "region_name": {
                      "type": "keyword"
                    }
                  }
                },
                "http_version": {
                  "type": "keyword"
                },
                "method": {
                  "type": "keyword"
                },
                "referrer": {
                  "type": "keyword"
                },
                "remote_ip_list": {
                  "index": true,
                  "store": false,
                  "type": "ip",
                  "doc_values": true
                },
                "response_code": {
                  "type": "long"
                },
                "url": {
                  "type": "wildcard"
                },
                "user_agent": {
                  "type": "object",
                  "properties": {
                    "device": {
                      "type": "keyword"
                    },
                    "name": {
                      "type": "keyword"
                    },
                    "original": {
                      "type": "keyword"
                    },
                    "os": {
                      "type": "keyword"
                    },
                    "os_name": {
                      "type": "keyword"
                    }
                  }
                },
                "user_name": {
                  "type": "keyword"
                }
              }
            },
            "error": {
              "type": "object",
              "properties": {
                "connection_id": {
                  "type": "long"
                },
                "level": {
                  "type": "keyword"
                },
                "message": {
                  "type": "text"
                },
                "process": {
                  "type": "long"
                },
                "tid": {
                  "type": "long"
                }
              }
            },
            "ingress_controller": {
              "type": "object",
              "properties": {
                "agent": {
                  "type": "keyword"
                },
                "body_sent": {
                  "type": "object",
                  "properties": {
                    "bytes": {
                      "type": "long"
                    }
                  }
                },
                "geoip": {
                  "type": "object",
                  "properties": {
                    "city_name": {
                      "type": "keyword"
                    },
                    "continent_name": {
                      "type": "keyword"
                    },
                    "country_iso_code": {
                      "type": "keyword"
                    },
                    "location": {
                      "type": "geo_point"
                    },
                    "region_iso_code": {
                      "type": "keyword"
                    },
                    "region_name": {
                      "type": "keyword"
                    }
                  }
                },
                "http": {
                  "type": "object",
                  "properties": {
                    "request": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "keyword"
                        },
                        "time": {
                          "type": "double"
                        },
                        "length": {
                          "type": "long"
                        }
                      }
                    }
                  }
                },
                "http_version": {
                  "type": "keyword"
                },
                "method": {
                  "type": "keyword"
                },
                "referrer": {
                  "type": "keyword"
                },
                "remote_ip_list": {
                  "eager_global_ordinals": false,
                  "norms": false,
                  "index": true,
                  "store": false,
                  "type": "keyword",
                  "index_options": "docs",
                  "split_queries_on_whitespace": false,
                  "doc_values": true
                },
                "response_code": {
                  "type": "long"
                },
                "upstream": {
                  "type": "object",
                  "properties": {
                    "alternative_name": {
                      "type": "keyword"
                    },
                    "ip": {
                      "type": "ip"
                    },
                    "name": {
                      "type": "keyword"
                    },
                    "port": {
                      "type": "long"
                    },
                    "response": {
                      "type": "object",
                      "properties": {
                        "length": {
                          "type": "long"
                        },
                        "length_list": {
                          "type": "keyword"
                        },
                        "status_code": {
                          "type": "long"
                        },
                        "status_code_list": {
                          "type": "keyword"
                        },
                        "time": {
                          "coerce": true,
                          "index": true,
                          "ignore_malformed": false,
                          "store": false,
                          "type": "double",
                          "doc_values": true
                        },
                        "time_list": {
                          "type": "keyword"
                        }
                      }
                    }
                  }
                },
                "upstream_address_list": {
                  "type": "keyword"
                },
                "url": {
                  "type": "wildcard"
                },
                "user_agent": {
                  "type": "object",
                  "properties": {
                    "device": {
                      "type": "keyword"
                    },
                    "name": {
                      "type": "keyword"
                    },
                    "original": {
                      "type": "keyword"
                    },
                    "os": {
                      "type": "keyword"
                    },
                    "os_name": {
                      "type": "keyword"
                    }
                  }
                },
                "user_name": {
                  "type": "keyword"
                }
              }
            }
          }
        }
      }
    }
  },
  "index_patterns": [
    "*-pfelk-nginx*"
  ],
  "data_stream": {
    "hidden": false
  },
  "composed_of": [
    "pfelk-settings",
    "pfelk-mappings-ecs"
  ],
  "_meta": {
    "description": "default nginx indexes installed by pfelk",
    "managed": true
  }
}
```

**Comment by BeNeDeLuX** [comment]
Perfect, your last template fixed the field. Thank you

**Pull request merged**
