### PR TITLE
36-ports-desc.conf

### PR DESCRIPTION
**Pull request by ShagoY**
## Description
Checks for the presense of the port field, if present runs translates the port into a referenced description.  

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by a3ilson — APPROVED** [review]

**Comment by a3ilson** [comment]
Thanks

**Comment by ShagoY** [comment]
Before using your project, I used "[pfsense-analytics](https://github.com/lephisto/pfsense-analytics)".
I liked the fact that I could translate "ports" into "services".
So I created this file for that and now I submit it to you.

**Comment by ShagoY** [comment]
Wow it's very fast for my first "pull-request" on github ^^

You have to add the associated panel and maybe something else like refreshing the index because I add [source][service] and [destination][service] :)

**Comment by ShagoY** [comment]
I also created the same thing but for the rules.
Using Opnsense, I don't have access to the command to link the description to the rule.
Moreover with a cvs file, I can update it simply and by using a "refresh_interval" of 60sec, my logstash is updated automatically (without having to restart logstash).

What do you think about it ?

**Comment by a3ilson** [comment]
I'll approve/incorporate later today! 

Thanks for your contributions and help!

**Pull request merged**
